### ISSUE TITLE
Playback error 🐇

### ISSUE THREAD

**Issue by moneytoo** [dburckh/ExoPlayer#12]
[big_buck_bunny_720p_surround.avi](https://archive.org/download/BigBuckBunny/big_buck_bunny_720p_surround.avi) is failing to play:

```
2022-01-31 18:47:03.423 9642-11107/com.google.android.exoplayer2.demo W/AviExtractor: Header length doesn't match stream length
2022-01-31 18:47:03.423 9642-11107/com.google.android.exoplayer2.demo W/AviExtractor: Header length doesn't match stream length
2022-01-31 18:47:03.441 9642-11107/com.google.android.exoplayer2.demo I/AviExtractor: Video chunks=53 us=596457379
2022-01-31 18:47:03.441 9642-11107/com.google.android.exoplayer2.demo I/AviExtractor: Audio #1 chunks: 38 us=596480000 size=136192
2022-01-31 18:47:03.455 9642-11107/com.google.android.exoplayer2.demo W/AviExtractor: Unknown tag=���� pos=65553 size=511848823 moviEnd=1218880
```

```
2022-01-31 18:45:33.838 9642-10928/com.google.android.exoplayer2.demo I/CCodec: state->set(RUNNING)
2022-01-31 18:45:33.838 9642-10928/com.google.android.exoplayer2.demo I/CCodecBufferChannel: [c2.dolby.eac3.decoder#834] 4 initial input buffers available
2022-01-31 18:45:33.840 9642-9642/com.google.android.exoplayer2.demo D/EventLogger: audioDecoderInitialized [eventTime=0.10, mediaPos=0.00, window=0, period=0, c2.dolby.eac3.decoder]
2022-01-31 18:45:33.841 9642-9642/com.google.android.exoplayer2.demo D/EventLogger: audioInputFormat [eventTime=0.10, mediaPos=0.00, window=0, period=0, id=1, mimeType=audio/ac3, channels=5, sample_rate=48000, label=BBB-Master]
2022-01-31 18:45:33.841 9642-9642/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=0.10, mediaPos=0.00, window=0, period=0, loadError
      com.google.android.exoplayer2.upstream.ContentDataSource$ContentDataSourceException
        at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:115)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
    ]
2022-01-31 18:45:33.851 9642-10920/com.google.android.exoplayer2.demo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:639)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.ContentDataSource$ContentDataSourceException
        at com.google.android.exoplayer2.upstream.ContentDataSource.open(ContentDataSource.java:115)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:776)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:589)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

Playback works fine when remuxed to mkv.

EDIT: Now I'm noticing it's _OpenDML_

**Comment by dburckh** [comment]
FYI:  Most of the files you have uploaded are hybrid AVI/OpenDML.  That's OK as long as they are muxed right.  I'm looking at this now.

**Comment by dburckh** [comment]
This is a sign something is wrong.  :) 

"Header length doesn't match stream length"

**Comment by dburckh** [comment]
MediaInfo is reporting it as OpenDML.  Maybe in a future release I can support it.  My goal was to support video from older and low end cameras.

**Comment by moneytoo** [comment]
Basically a duplicate of #8
